### [bt]: This is batchtools v0.9.15
### [bt]: Starting calculation of 1 jobs
### [bt]: Setting working directory to '/projects/genomic-ml/sub-quadratic-full-gradient-AUC-optimization/app'
### [bt]: Memory measurement disabled
### [bt]: Starting job [batchtools job.id=181]
### [bt]: Setting seed to 19255 ...
2021-10-01 11:50:47.121792: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /packages/gcc-8.3.1/R/4.1.0/lib64/R/lib:/usr/local/lib64:/etc/alternatives/jre_openjdk/lib/amd64/server:/packages/gcc-8.3.1/R/4.1.0/lib64/R/lib:/usr/local/lib64:/etc/alternatives/jre_openjdk/lib/amd64/server:/packages/gcc-8.3.1/netcdf-c/4.7.4-opdm2fw/lib:/packages/libtiff/4.1.0/lib:/packages/gcc-8.3.1/geos/3.8.1-j7t4spf/lib:/packages/gcc-8.3.1/proj/7.1.0/lib:/packages/gdal/3.3.1/lib:/packages/gcc-8.3.1/R/4.1.0/lib64/R/lib
2021-10-01 11:50:47.121834: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
torch 1.9.1
torchvision 0.10.1+cu102
NUM_SAMPLES: [25252], POS:NEG: [252 : 25000], POS_RATIO: 0.0100
NUM_SAMPLES: [10000], POS:NEG: [5000 : 5000], POS_RATIO: 0.5000
Epoch: 0
/home/th798/.conda/envs/emacs1/lib/python3.7/site-packages/torchmetrics/utilities/prints.py:36: UserWarning: Metric `AUROC` will save all targets and predictions in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
train
torch.Size([25000, 1]) torch.Size([25000, 1])
test
/home/th798/.conda/envs/emacs1/lib/python3.7/site-packages/torchmetrics/utilities/prints.py:36: UserWarning: `pos_label` automatically set 1.
  warnings.warn(*args, **kwargs)
torch.Size([10000, 1]) torch.Size([10000, 1])
Epoch: 1
train
torch.Size([25000, 1]) torch.Size([25000, 1])
test
torch.Size([10000, 1]) torch.Size([10000, 1])
Epoch: 2
train
torch.Size([25000, 1]) torch.Size([25000, 1])
test
torch.Size([10000, 1]) torch.Size([10000, 1])
Epoch: 3
train
torch.Size([25000, 1]) torch.Size([25000, 1])
test
torch.Size([10000, 1]) torch.Size([10000, 1])
Epoch: 4
train
torch.Size([25000, 1]) torch.Size([25000, 1])
test
torch.Size([10000, 1]) torch.Size([10000, 1])
Epoch: 5
train
torch.Size([25000, 1]) torch.Size([25000, 1])
test
torch.Size([10000, 1]) torch.Size([10000, 1])
Epoch: 6
/home/th798/.conda/envs/emacs1/lib/python3.7/site-packages/torch/autograd/__init__.py:149: UserWarning: Error detected in MulBackward0. Traceback of forward call that caused the error:
  File "driver.py", line 23, in <module>
    float(lr))
  File "/projects/genomic-ml/sub-quadratic-full-gradient-AUC-optimization/app/convolutional_NN.py", line 67, in train_classifier
    loss = loss_function(outputs, targets)
  File "/projects/genomic-ml/sub-quadratic-full-gradient-AUC-optimization/app/functional_square_hinge_loss.py", line 29, in functional_square_hinge_loss
    running_loss += a_coeff*(predicted_value**2) + b_coeff*(predicted_value) + c_coeff
 (Triggered internally at  /opt/conda/conda-bld/pytorch_1631630742027/work/torch/csrc/autograd/python_anomaly_mode.cpp:104.)
  allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
Traceback (most recent call last):
  File "driver.py", line 23, in <module>
    float(lr))
  File "/projects/genomic-ml/sub-quadratic-full-gradient-AUC-optimization/app/convolutional_NN.py", line 69, in train_classifier
    loss.backward()
  File "/home/th798/.conda/envs/emacs1/lib/python3.7/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/th798/.conda/envs/emacs1/lib/python3.7/site-packages/torch/autograd/__init__.py", line 149, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: Function 'MulBackward0' returned nan values in its 0th output.

### [bt]: Job terminated successfully [batchtools job.id=181]
### [bt]: Calculation finished!
